import { useState } from "react";
import Head from "next/head";

import LoadingSection from "@/components/LoadingSection";
import MainSection from "@/components/MainSection";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  return (
    <>
      <Head>
        <title>Sample Gamified App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isLoading ? (
          <LoadingSection onFinish={() => setIsLoading(false)} />
        ) : (
          <MainSection />
        )}
      </main>
    </>
  );
}
